-- CREATE USER TABLE
DROP TABLE users IF EXISTS;
DROP TABLE questions IF EXISTS;
DROP TABLE answers IF EXISTS;
DROP ENUM question_type IF EXISTS;
DROP TABLE forms IF EXISTS;
DROP TABLE options IF EXISTS;
