DROP TABLE IF EXISTS volunteers_events;
DROP TABLE IF EXISTS volunteers;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS ticket_type;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
-- CREATE USER TABLE
