services: 
  backend: 
    build: ..
    restart: always
    ports: 
      - 8090:8090
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gultix?sslmode=disable
      - PORT=8090
      - CLIENT_ID=
      - CLIENT_SECRET=
      - REDIRECT_URL=
      - JWT_SECRET=supersecret
      - JWT_EXPIRED_TIME=2h
      - JWT_ISSUER=Gultix-Backend-Dev
      - MIDTRANS_SERVER_KEY=
      - ENV=dev
    depends_on: 
      - db
  
  db: 
    image: postgres:alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gultix
    volumes: 
      - db:/var/lib/postgres/data

  pg-admin:
    image: dpage/pgadmin4:8.9
    restart: always 
    environment: 
      - PGADMIN_DEFAULT_EMAIL=postgres@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_WTF_CSRF_HEADERS='["Referer", "Origin"]'
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED='False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on: 
      - db

volumes: 
  db:
  pgadmin:
  